### ISSUE TITLE
Type관련 이슈

### ISSUE THREAD

**Issue by krung2** [BambooForest-for-GSM/Bamboo-API#34]
`Typescript`를 사용하는 만큼 각각 `type`을 지정해주는 것이 좋아보입니다
- ps 각 변수에 `type`을 지정하고, 함수에도 `return type`을 지정해주는 것이 좋아보입니다

**Comment by sunrabbit123** [comment]
#39 에서 야무지게 처리해보았습니다. 코드리뷰 감사합니다!!
